src/NerdStore.WebApp.MVC/Controllers/Admin/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalog.Application.Services;
using NerdStore.Core.Bus;
using NerdStore.Sales.Application.Commands;

namespace NerdStore.WebApp.MVC.Controllers.Admin
{
    public class CartController : ControllerBase
    {
        private readonly IProductAppService _productAppService;
        private readonly IMediatorHandler _mediatorHandler;

        public CartController(
            IProductAppService productAppService,
            IMediatorHandler mediatorHandler)
        {
            _productAppService = productAppService;
            _mediatorHandler = mediatorHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetById(id);
            if (product == null) return BadRequest();

            if (product.StockQuantity < quantity)
            {
                TempData["Error"] = "The product has insufficient stock.";
                return RedirectToAction("ProductDetails", "ShopWindow", new { id });
            }

            var command = new AddOrderItemCommand(ClientId, product.Id, product.Name, quantity, product.Price);
            var success = await _mediatorHandler.SendCommand(command);

            //if (success)
            //{
                    
            //}
            //else
            //{

            //}


            TempData["Error"] = "Product unavailable";
            return RedirectToAction("ProductDetails", "ShopWindow", new { id });

        }


    }
}

src/NerdStore.WebApp.MVC/Controllers/CartController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalog.Application.Services;
using NerdStore.Core.Communication.Mediator;
using NerdStore.Core.Messages.CommonMessages.Notifications;
using NerdStore.Sales.Application.Commands;
using NerdStore.Sales.Application.Queries;
using System;
using System.Threading.Tasks;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class CartController : ControllerBase
    {
        private readonly IProductAppService _productAppService;
        private readonly IOrderQueries _orderQueries;
        private readonly IMediatorHandler _mediatorHandler;

        public CartController(INotificationHandler<DomainNotification> notifications,
                              IProductAppService productAppService,
                              IMediatorHandler mediatorHandler,
                              IOrderQueries orderQueries) : base(notifications, mediatorHandler)
        {
            _productAppService = productAppService;
            _mediatorHandler = mediatorHandler;
            _orderQueries = orderQueries;
        }

        [Route("my-cart")]
        public async Task<IActionResult> Index()
        {
            return View(await _orderQueries.GetCartByClientId(ClientId));
        }

        [HttpPost]
        [Route("my-cart")]
        public async Task<IActionResult> AddItem(Guid id, int quantity)
        {
            var product = await _productAppService.GetById(id);
            if (product == null) return BadRequest();

            if (product.StockQuantity < quantity)
            {
                TempData["Error"] = "The product has insufficient stock.";
                return RedirectToAction("ProductDetails", "ShopWindow", new { id });
            }

            var command = new AddOrderItemCommand(ClientId, product.Id, product.Name, quantity, product.Price);
            await _mediatorHandler.SendCommand(command).ConfigureAwait(true);

            if (IsOperationValid())
            {
                return RedirectToAction("Index");
            }

            TempData["Errors"] = GetErrorMessages();
            return RedirectToAction("ProductDetails", "ShopWindow", new { id });

        }

        [HttpPost]
        [Route("apply-voucher")]
        public async Task<IActionResult> ApplyVoucher(string voucherCode)
        {
            var command = new ApplyVoucherOrderCommand(ClientId, voucherCode);
            await _mediatorHandler.SendCommand(command).ConfigureAwait(true);

            if (IsOperationValid())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _orderQueries.GetCartByClientId(ClientId));
        }


    }
}

src/NerdStore.WebApp.MVC/Extensions/SummaryViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Messages.CommonMessages.Notifications;
using System.Threading.Tasks;

namespace NerdStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifications = await Task.FromResult(_notifications.GetNotifications());
            notifications.ForEach(n => ViewData.ModelState.AddModelError(string.Empty, n.Value));

            return View();
        }

    }
}

src/NerdStore.WebApp.MVC/Views/Cart/Index.cshtml
@model NerdStore.Sales.Application.Queries.ViewModels.CartViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">

            <vc:summary />

            @{
                if (Model?.Items != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Qty</th>
                                <th class="text-center">Sub Total</th>
                                <th class="text-center">Total</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            @{
                                foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td class="col-sm-5 col-md-5">
                                            <div class="media">
                                                <div class="media-body">
                                                    <h4 class="media-heading"><a asp-controller="ShopWindow" asp-action="ProductDetails" asp-route-id="@item.ProductId">@item.ProductName</a></h4>
                                                </div>
                                            </div>
                                        </td>

                                        <td class="col-sm-2 col-md-2" style="text-align: center">
                                            <form method="post" asp-controller="Cart" asp-action="UpdateItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <div class="row" style="float: left">
                                                    <input style="width: 70px" type="text" class="form-control" name="quantity" id="quantity" value="@item.Quantity">
                                                </div>
                                                <div class="row" style="float: right">
                                                    <button type="submit" class="btn btn-success">
                                                        <span class="fas fa-sync"></span>
                                                    </button>
                                                </div>
                                            </form>
                                        </td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.UnitPrice.ToString("C")</strong></td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.Total.ToString("C")</strong></td>

                                        <td class="col-sm-1 col-md-1">
                                            <form method="post" asp-controller="Cart" asp-action="RemoveItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProductId" />
                                                <button type="submit" class="btn btn-danger">
                                                    <span class="fas fa-trash-alt"></span> Remove
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            }

                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td><h5>Subtotal</h5></td>
                                <td class="text-right"><h5><strong>@Model.SubTotal.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td colspan="2">
                                    <form method="post" asp-controller="Cart" asp-action="ApplyVoucher">
                                        <div class="row" style="float: left">
                                            <input placeholder="Voucher" style="width: 150px" type="text" class="form-control" name="VoucherCode" id="VoucherCode" value="@Model.VoucherCode">
                                        </div>
                                        <div class="row" style="float: right">
                                            <button type="submit" class="btn btn-success">
                                                <span class="fas fa-sync"></span>
                                            </button>
                                        </div>
                                    </form>
                                </td>
                                <td><h5>Discount</h5></td>
                                <td class="text-right"><h5><strong>@Model.Discount.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <h3>Total</h3>
                                </td>
                                <td class="text-right">
                                    <h3><strong>@Model.TotalOrder.ToString("C")</strong></h3>
                                </td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <a asp-controller="ShopWindow" asp-action="Index" class="btn btn-dark">
                                        <span class="fa fa-shopping-cart"></span>Continuing Shopping
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="Cart" asp-action="OrderDetails" class="btn btn-success">
                                        <span class="fas fa-play"></span><br /> Go to Checkout
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }
                else
                {
                    <div><p>Cart empty</p></div>
                }
            }
        </div>
    </div>
</div>